### ISSUE TITLE
Plugin does not allow any other user to take a test other than the 'administrators'

### ISSUE THREAD

**Issue by harunthuo** [grantnorwood/wp-pro-quiz#2]
when signed in as an administrator, i can take a test and on finishing, the results are displayed in the back end in the 'statistics' and an email is also sent to the site admin that a user has just completed a test.

however, when i sign in as another user (either customer, subscriber e.t.c), i can't take a test (this is when a question has been set only for registered users). what could be the issue?

**Comment by grantnorwood** [comment]
It sounds like the code is requiring the Administrator role, though it should probably allow other roles (subscriber, contributor, author, etc) as well.  Honestly, I am not the original author on this plugin, I forked this from the [WP Pro Quiz](https://wordpress.org/plugins/wp-pro-quiz/) plugin on WordPress.org over 2 years ago.

Perhaps try downloading the latest version of the official plugin from the WordPress plugin repository, or forking the latest version from the original author's GitHub repo at https://github.com/xeno010/Wp-Pro-Quiz.  If the functionality you need is still not there, I'm sure the author would appreciate you adding the feature and sending a pull request to contribute your fix!

Good luck!
